version: '3.9'

services:

  reverse-proxy:
    image: nginx:1.19.10
    container_name: reverse_proxy_demo
#    depends_on:

    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
#      - ./home/dxglide/Development/docker_stuff/logs:/var/log/nginx
    ports:
      - 8080:80

  simple-rest:
    image: dxglide/simple-rest-docker
    container_name: name1
##    build:
##      context: ./linkas
##    depends_on:
    ports:
      - 8081:8081
    restart: on-failure

  simple-rest2:
    image: dxglide/simple-rest-docker
    container_name: name2
    ##    build:
    ##      context: ./linkas
    ##    depends_on:
    ports:
      - 8082:8082
    restart: on-failure
